version: "3.9"
   
services:
  db:
    build: 
      context: ./docker_container/elasticsearch/
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
    networks: 
      - qas_net
  python_core:
    build: ./docker_container/python_core/
    image: python_core
  web:
    build: 
      context: .
    command: > 
      bash -c "./wait-for-it.sh -t 25 db:9200 -- python initial_data_load.py
      && python manage.py makemigrations backend_app
      && python manage.py migrate
      && echo '### QAS-CORD19 STARTING ###' 
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./django_backend:/django_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - python_core
    networks: 
      - qas_net
networks:
  qas_net: